#!/usr/bin/env ruby

$finished = false

require 'fileutils'
require 'Yk/debug2'

if ARGV.size != 2
	STDERR.write "USAGE: cp_noerror SRC_DIR DEST_DIR"
	exit 1
end


SRC = ARGV[0]
DST = ARGV[1]
$cntP = 0.0
$szP = 0.0


MSG_D = "/tmp/cp_noerror"


FileUtils.mkdir_p MSG_D

$ef = "#{MSG_D}/cp_noerror.#{$$}"

newest = Time.at(0)
newestF = nil


OKList = {}

Dir.glob MSG_D + "/cp_noerror.*.ok" do |e|
	File.open e do |fr|
		fr.each_line do |ln|
			if ln =~ /^.*\|(.*):[^:]*$/
				OKList[$1] = true
			end
		end
	end
#	if File.mtime(e) > newest
#		newest = File.mtime(e)
#		newestF = e
#	end
end


#if File.exist? newestF
#	File.open newestF do |fr|
#		fr.each_line do |ln|
#			if ln =~ /^.*\|(.*):[^:]*$/
#				OKList[$1] = true
#			end
#		end
#	end
#end


def out f, m, *fs
	m = "#{Time.now} #{$finished ? '' : '('}#{sprintf '%.1f', $cntP}%#{$finished ? '' : ')'}|#{f}:#{m}.\n"
	msgpane
	print m
	["", *fs].each do |ext|
		File.append $ef + ext, m
	end
end

def msg f, m
	out f, m
end

def err f, m
	out f, m, ".err"
	print "\n\n\n\n\n\n\n\n\n\n"
	print "\033[u"
end

def ok f
	out f, "Processed successfully", ".ok"
end


class String
	def / arg
		if arg[0] == "/"
			arg
		elsif self.empty?
			arg
		elsif arg == "" || arg == nil
			if self[-1] == "/"
				self.chop
			else
				self
			end
		else
			if self[-1] == "/"
				self + arg
			else
				self + "/" + arg
			end
		end
	end
end


class File
  class << self
    def append(path, content)
      File.open(path, "a") { |f| f << content }
    end
  end
end

def msgpane
	print "\033[u"
	print "\033[B\033[K"
	print "\033[B\033[K"
	print "\033[B\033[K"
	print "\033[B\033[K"
	print "\033[B\033[K"
	print "\033[B\033[K"
	print "\033[B\033[K"
	print "\033[B\033[K"
	print "\033[B\033[K"
	print "\033[B\033[K"
	print "\033[u"
	STDOUT.flush
end


def psNodeNum pid
	children = Hash.new do |h, k|
		h[k] = Array.new
	end
	`ps ax -o 'pid ppid'`.each_line do |ln|
		arr = ln.split
		children[arr[1]].push arr[0]
	end
	getChildren = Proc.new do |c|
		cls = children[c]
		ret = cls.clone
		cls.each do |d|
			ret += getChildren[d]
		end
		ret
	end
	getChildren[pid].size
end


def each_dir dir = ""
	if OKList[dir]
		msg dir, "Already processed"
		return
	end
	msg(dir == "" ? "." : dir, "processing directory")
	s = SRC / dir
	d = DST / dir
	if File.symlink?(s) || !File.directory?(s)
		STDERR.write "ERROR: The source path, '#{s}' is not a directory\n"
		exit 1
	end
	begin
		if File.symlink?(d) || (File.exist?(d) && !File.directory?(d))
			FileUtils.rm_f d
		end
		FileUtils.mkdir_p d
		stat = File.stat(s)
		FileUtils.chmod(stat.mode, d)
		FileUtils.chown(stat.uid, stat.gid, d)
		FileUtils.touch(d, mtime: stat.mtime)
	rescue
		err dir, "Failed to mkdir/copy attributes (#{$!}). Skipping"
		return
	end
	begin
		failed = false
		Dir.foreach s do |f|
			sf = s / f
			df = d / f
			t = dir / f
			if OKList[t]
				msg t, "Already processed"
				next
			end
			if f != "." && f != ".."
				begin
					if !File.symlink?(sf) && File.directory?(sf)
						incProcessed t do
							each_dir t
						end
					else
						msg t, "processing non-directory entry"
						if File.symlink?(sf) || File.symlink?(df)
							FileUtils.rm_f(df)
						end
						if !File.symlink?(sf) && File.file?(sf)
							begin
								if File.symlink?(df) || !File.file?(df)
									FileUtils.rm_f df
								end
								sz = File.lstat(sf).size
								if sz > 100000000
									pid = fork do
										exec "/usr/bin/rsync", "-avc", "--info=progress2", sf, df
									end
									Thread.abort_on_exception = true
									Thread.new do
										#begin
											sleep 0.1
											fd = nil
											if File.exist? "/proc/#{pid}/fd"
												Dir.foreach "/proc/#{pid}/fd" do |fent|
													_s = "/proc/#{pid}/fd/#{fent}"
													if File.symlink?(_s) && File.readlink(_s) == sf
														fd = fent
														break
													end
												end
												if fd
													sz = File.size sf
													print "\n"
													while psNodeNum(pid) <= 2
														if File.exist? "/proc/#{pid}/fdinfo/#{fd}"
															IO.read("/proc/#{pid}/fdinfo/#{fd}").each_line do |ln|
																if ln =~ /^pos:\s*(\d+)/
																	tmp = sprintf "%.1f", ($1.to_f / sz) * 100
																	print "\033[0GScanning ... #{tmp} %\033[K"
																	STDOUT.flush
																end
															end
														else
															break
														end
														sleep 1
													end
												end
											end
										#rescue
										#end
									end
									t2 = Process.detach pid
									if t2.value.to_i != 0
										err t, "Failed to rsync #{sf} #{df}. Skipping"
									else
										ok t
									end
								else
									if !system "/usr/bin/rsync", "-ac", sf, df
										err t, "Failed to rsync #{sf} #{df}. Skipping"
									else
										ok t
									end
								end
							rescue => e
								failed = true
								err t, "Failed to copy entry (#{e}:#{e.backtrace[0]}). Skipping"
							end
						else
							if !system "/bin/cp", "-af", sf, df
								failed = true
								err t, "Failed to copy entry ('/bin/cp -af #{sf} #{df}', failed). Skipping"
							else
								ok t
							end
						end
						incProcessed t
					end
				rescue => e
					failed = true
					err t, "Failed to stat entry (#{e}:#{e.backtrace[0]}). Skipping"
				end
			end
		end
	rescue => e
		err dir, "Failed to read directory entry (#{e}:#{e.backtrace[1]}). Skipping"
		return
	end
	if !failed
		ok dir
	end
end

print "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
STDOUT.flush

print "\033[15A\033[s"
STDOUT.flush


CntProgs = Hash.new do |h, k|
	h[k] = 0
end

SzProgs = Hash.new do |h, k|
	h[k] = 0
end

$all_cnt = 0
$all_sz = 0

def all_size dir = ""
	s = SRC / dir
	Dir.foreach s do |e|
		if e == "." || e == ".."
			next
		end
		f = s / e
		if !File.symlink?(f) && File.directory?(f)
			all_size dir / e
		else
			$all_cnt += 1
			$all_sz += File.lstat(f).size
			CntProgs[dir / e] = $all_cnt
			SzProgs[dir / e] = $all_sz
		end
	end
	$all_cnt += 1
	$all_sz += File.lstat(s).size
	CntProgs[dir] = $all_cnt
	SzProgs[dir] = $all_sz
end

Thread.new do
	all_size
	$finished = true
end


def incProcessed t = ""
	begin
		if block_given?
			yield
		end
	ensure
		$cntP = (CntProgs[t].to_f / $all_cnt * 100) rescue 0.to_f
		$szP = (SzProgs[t].to_f / $all_sz * 100) rescue 0.to_f
	end
end

incProcessed do
	each_dir
end

